---
title: CRAN Usage
author: Mark Sellors
date: "`r Sys.Date()`"
output:
  html_document:
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)
```
<details>
    <summary>Get and read the log</summary>

Get and read the log file.

```{r get_log}
yesterday <- Sys.Date()-1
year <- format(Sys.time(), "%Y")
url <- paste0('http://cran-logs.rstudio.com/', year, '/', yesterday, '.csv.gz')
filename <- paste0(yesterday, '.csv.gz')
if ( !file.exists(filename) ){
  cat(paste0("Downloading: ", filename))
  download.file(url, destfile = filename)
}
cranlog <- read.csv(gzfile(filename))
```
</details>


### Yesterday, there were `r format(length(cranlog$ip_id), big.mark=",")` distinct package downloads and `r format(length(unique(cranlog$ip_id)), big.mark=",")` unique users on `r yesterday`.

---

# By R version

```{r r_version, fig.width=10}
barplot(table(cranlog$r_version), las = 2, cex.names = 1.3)
```


# By OS

```{r by_os, fig.width=10}
r_os_macos <- gsub("^darwin.*", "MacOS", cranlog$r_os)
r_os <- gsub("mingw32", "Windows", r_os_macos)
barplot(table(r_os))
```

# By Architecture

````{r by_arch, fig.width=10}
barplot(table(cranlog$r_arch), cex.names = .8)
```

Another [@sellorm](https://twitter.com/sellorm) rough cut.