# Controls when the action will run, in this case a schedule.
on:
  schedule:
  - cron: "0 4 * * *"

name: rmarkdown-render

jobs:
  pkgdown:
    runs-on: ubuntu-focal
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: install linux deps
        run: make linux-deps

      - name: render the rmarkdown doc
        run: make docs

      - name: Install package
        run: R CMD INSTALL .

      # Runs a set of commands using the runners shell
      - name: Push the changes back to the repo
        run: |
          git add -f docs/index.html
          git commit -am "Automated GitHub action commit"
          git push --force --set-upstream origin netlify
