# Controls when the action will run, in this case a schedule.
on:
  schedule:
  - cron: "15 17 * * *"
  
  workflow_dispatch:

name: rmarkdown-render

jobs:
  rmdrender:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: install linux deps
        run: make focal-deps

      - name: render the rmarkdown doc
        run: make docs

      - name: git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions committer"
      
      - name: Push the changes back to the repo
        run: |
          git add -f docs/*
          git commit -am "Automated GitHub action commit"
          git push --force --set-upstream origin main
